### ISSUE TITLE
If I want to support querying a new language X, what kind of adaptations and modifications do I need to make in which modules or subfolders? Are there any development manuals and documentation?

### ISSUE THREAD

**Issue by Bambi66669** [github/codeql#15201]
If I want to support querying a new language X, what kind of adaptations and modifications do I need to make in which modules or subfolders? Are there any development manuals and documentation?

_Originally posted by @Sucan2 in https://github.com/github/codeql/discussions/15177_
```[tasklist]
### Tasks
- [ ] https://github.com/github/codeql/pull/15189
- [ ] https://github.com/github/codeql/pull/15194
- [ ] https://github.com/github/codeql/issues/15199
- [ ] https://github.com/github/codeql/pull/15197
- [ ] https://github.com/github/codeql/pull/14123
```

```[tasklist]
### Tasks
```
