### ISSUE TITLE
Java: Data Flow Tracking for Stream/Promise based data flow

### ISSUE THREAD

**Issue by JLLeitschuh** [github/codeql#4988]
**Description of the issue**

Data flow tracking doesn't currently work when the flow source uses non-procedural based data flow and instead uses stream or asynchronous paradigms.

A few examples:
 - [ ] Java 8 Streams APIs
 - [ ] Java 8 `CompletableFuture`
 - [ ] RX Java
 - [ ] Third party library implementations of `Proimise`
	 - [ ] Ratpack [Promise](https://ratpack.io/manual/current/api/ratpack/exec/Promise.html)

Javascript has support for this library.
https://github.com/github/codeql/blob/main/javascript/ql/src/semmle/javascript/Promises.qll

Having a similar generic & extendable API would be appreciated.
